# Use Python base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the Python script and requirements file to the working directory
COPY ml-model.py /app/
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set the default command to run the Python script
CMD ["python", "/app/ml-model.py"]
